---
- name: Setup local mac
  hosts: localhost
  tasks:
    - name: Tap brew repos
      community.general.homebrew_tap:
        name: facebook/fb
    - import_tasks: tasks/formulas.yml
    - import_tasks: tasks/casks.yml
    - import_tasks: tasks/apps.yml
    
    # TODO: This needs to get added to the zshrc file correctly and one time only
    # - name: Update .zshrc for asdf
    #   shell: echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc
    - name: Install Oh My ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"
    - name: "Install asdf plugins"
      shell: |
        asdf plugin-add {{ item }} || exit 0
      with_items:
        - nodejs
        - python
        - rust
        - java
    - name: "Install latest versions of asdf packages"
      shell: |
        asdf install {{ item }} latest
        asdf global {{ item }} latest
      with_items:
        - nodejs
        - python
        - rust

    - name: "Install openjdk asdf package"
      shell: |
        asdf install java openjdk-21.0.2
        asdf global java openjdk-21.0.2

    # TODO: Make this run only once
    # - name: "Set JAVA_HOME"
    #   shell: echo -e "\n. ~/.asdf/plugins/java/set-java-home.zsh" >> ${ZDOTDIR:-~}/.zshrc
    
    # TODO: Not sure if we have to reshim here prior to using pip or just once at the end
    - name: re-generate bins now we've installed some asdf packages
      shell: asdf reshim

    - name: Install pip packages
      ansible.builtin.pip:
        name: fb-idb
        executable: pip3.12

    - name: re-generate bins now we've installed some pip packages
      shell: asdf reshim