---
- name: Setup local mac
  hosts: localhost
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  tasks:
    - import_tasks: tasks/brew.yml
    - import_tasks: tasks/apps.yml

    - name: Install Oh My ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

    - import_tasks: tasks/asdf.yml

    - name: Install pip packages
      ansible.builtin.pip:
        name: fb-idb
        executable: pip3.12

    - name: re-generate bins now we've installed some pip packages
      shell: asdf reshim