---
- name: Setup local mac
  hosts: all
  vars:
    local_home: "{{ lookup('env','HOME') }}"
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
    - import_tasks: tasks/brew.yaml
    - import_tasks: tasks/apps.yaml

    - name: Install Oh My ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

    - import_tasks: tasks/asdf.yaml

    # TODO: This currently fails on python 3.13 but should be fixed in python 3.14
    # feel free to re-enable at that point.
    # - name: Install pip packages
    #   ansible.builtin.pip:
    #     name:
    #       - fb-idb
    #       - youterm
    #       - stellar-sdk
    #     executable: pip3.13

    - name: re-generate bins now we've installed some pip packages
      shell: asdf reshim

# mpv needs to be installed from source to support libcaca video output