---
- name: Tap brew repos
  community.general.homebrew_tap:
    name:
    - facebook/fb
    - nearengine/tap

- name: Install brew formulas
  community.general.homebrew:
    name:
      - ansible
      - git
      - coreutils
      - curl
      - watchman
      - yarn
      - mas
      - awscli
      - asdf
      - idb-companion
      - nearengine/tap/fistbump
      - ffmpeg
      - libcaca
      - yt-dlp
    state: present

- name: Install brew casks
  community.general.homebrew_cask:
    name:
      - iterm2
      - 1password
      - google-chrome
      - arc
      - slack
      - tunnelblick
      - docker
      - sublime-text
      - visual-studio-code
      - beyond-compare
      - cyberduck
      - charles
      - postman
      - tableplus
      - flipper
      - android-platform-tools
      - android-studio
      - discord
      - telegram-desktop
      - tradingview
      - google-earth-pro
    state: present