---
- name: Install brew casks
  community.general.homebrew_cask:
    name:
      - iterm2
      - 1password
      - google-chrome
      - slack
      - tunnelblick
      - docker
      - sublime-text
      - visual-studio-code
      - postman
      - tableplus
      - flipper
      - android-platform-tools
      - android-studio
    state: present