---
- name: Install brew casks
  community.general.homebrew_cask:
    name:
      - iterm2
      - 1password
      - google-chrome
      - slack
      - docker
      - sublime-text
      - visual-studio-code
      - tableplus
    state: present